config/routes.rb
Rails.application.routes.draw do

  resources :orders, :only => [:index] do
    collection do
      get 'asynchronous'
      get 'synchronous'
      get 'take_order'
    end
  end

  root 'orders#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
  end

  def asynchronous
  end

  def synchronous
  end

  def take_order
    sleep params[:items].to_i
    render :nothing => true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <h1>Welcome to BitBurger</h1>

  <p>IMPORTANT NOTE - if we run the default Rails server (Webrick), BitBurger will only have 1 cook to take our orders (it can only process 1 request at at time).</p>
  <p>To employ more than 1 cook to process orders at the same time, we will need to run something that supports concurrent requests as our server. A popular production option for Rails that fits this description would be Unicorn.</p>

  <p>For our example, each item in an order will take 1 second to cook. Orders with more items will naturally take longer to complete.</p>

  <%= yield %>

</body>
</html>

app/views/orders/asynchronous.html.erb
<h2>Asynchronous Model</h2>

<h3>Cashier 1</h3>

<div class="order" id="john"></div>
<p>
  <%= link_to "Take Order for John (6 Items)", take_order_orders_path(:items => 6), :class => "take-order-button", :data => {:name => "john"} %>
</p>
<div class="order" id="jane"></div>
<p>
  <%= link_to "Take Order for Jane (1 Item)", take_order_orders_path(:items => 1), :class => "take-order-button", :data => {:name => "jane"} %>
</p>
<div class="order" id="sally"></div>
<p>
  <%= link_to "Take Order for Sally (4 Items)", take_order_orders_path(:items => 4), :class => "take-order-button", :data => {:name => "sally"} %>
</p>

<script>

  $(document).ready(function() {

    // Set up an event listener to take orders
    $('.take-order-button').on('click', function(e) {
      // Prevent link from doing its usual thing
      e.preventDefault();
      // Take note of the customer's name
      var customerName = $(this).attr("data-name");
      // Update status to show we have sent the order to a cook
      $('#' + customerName).html("<em>Sent to cook...</em>");
      // Send order to a cook and keep track of the name so we can update them when done
      // We will use the original link's href as the target for the ajax request
      $.ajax({
        url: $(this).attr("href")
      }).done(function() {
        $('#' + customerName).html("<em class='order-complete'>Ding Ding. Order Up!!</em>");
      });
    });

  });

</script>

app/views/orders/index.html.erb
<p><%= link_to "I Want Synchronous Fast Food", "/orders/synchronous" %></p>
<p><%= link_to "I Want Asynchronous Fast Food", "/orders/asynchronous" %></p>

app/views/orders/synchronous.html.erb
<h2>Synchronous Model</h2>

<p class="red">NOTE - when we set the ajax option async to false, we are not even able to click on another link if the first request is not completed. We are basically telling the browser's JS engine that you can only do one thing a time.</p>

<h3>Cashier 1</h3>
<div class="order" id="john"></div>
<p>
  <%= link_to "Take Order for John (6 Items)", take_order_orders_path(:items => 6), :class => "take-order-button", :data => {:name => "john"} %>
</p>

<h3>Cashier 2</h3>
<div class="order" id="jane"></div>
<p>
  <%= link_to "Take Order for Jane (1 Item)", take_order_orders_path(:items => 1), :class => "take-order-button", :data => {:name => "jane"} %>
</p>

<h3>Cashier 3</h3>
<div class="order" id="sally"></div>
<p>
  <%= link_to "Take Order for Sally (4 Items)", take_order_orders_path(:items => 4), :class => "take-order-button", :data => {:name => "sally"} %>
</p>


<script>

  $(document).ready(function() {

    // Set up an event listener to take orders
    $('.take-order-button').on('click', function(e) {
      // Prevent link from doing its usual thing
      e.preventDefault();
      // Take note of the customer's name
      var customerName = $(this).attr("data-name");
      // Send order to a cook and keep track of the name so we can update them when done
      // We will use the original link's href as the target for the ajax request
      $.ajax({
        url: $(this).attr("href"),
        async: false
      }).done(function() {
        $('#' + customerName).html("<em class='order-complete'>Ding Ding. Order Up!!</em>");
        $('.take-order-button').show();
      });
    });

  });

</script>